# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CommandMsg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CommandMsg.proto',
  package='schemas',
  serialized_pb=_b('\n\x10\x43ommandMsg.proto\x12\x07schemas\"f\n\x12\x44\x65viceCommandProto\x12\r\n\x05msgId\x18\x01 \x02(\t\x12\x0f\n\x07version\x18\x02 \x02(\x05\x12\x0e\n\x06hostId\x18\x03 \x02(\t\x12\x0f\n\x07\x63mdType\x18\x04 \x02(\x05\x12\x0f\n\x07payload\x18\x05 \x01(\t\"\x88\x01\n\x15\x44\x65viceCommandResProto\x12\r\n\x05msgId\x18\x01 \x02(\t\x12\x0f\n\x07version\x18\x02 \x02(\x05\x12\x0e\n\x06hostId\x18\x03 \x02(\t\x12\r\n\x05\x63mdId\x18\x04 \x02(\t\x12\x0e\n\x06result\x18\x05 \x02(\t\x12\x0f\n\x07payload\x18\x06 \x01(\t\x12\x0f\n\x07\x63mdType\x18\x07 \x01(\x05\x42#\n!com.segmetics.ng.protocol.message')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DEVICECOMMANDPROTO = _descriptor.Descriptor(
  name='DeviceCommandProto',
  full_name='schemas.DeviceCommandProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgId', full_name='schemas.DeviceCommandProto.msgId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='schemas.DeviceCommandProto.version', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hostId', full_name='schemas.DeviceCommandProto.hostId', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cmdType', full_name='schemas.DeviceCommandProto.cmdType', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payload', full_name='schemas.DeviceCommandProto.payload', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=131,
)


_DEVICECOMMANDRESPROTO = _descriptor.Descriptor(
  name='DeviceCommandResProto',
  full_name='schemas.DeviceCommandResProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgId', full_name='schemas.DeviceCommandResProto.msgId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='schemas.DeviceCommandResProto.version', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hostId', full_name='schemas.DeviceCommandResProto.hostId', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cmdId', full_name='schemas.DeviceCommandResProto.cmdId', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result', full_name='schemas.DeviceCommandResProto.result', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payload', full_name='schemas.DeviceCommandResProto.payload', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cmdType', full_name='schemas.DeviceCommandResProto.cmdType', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=270,
)

DESCRIPTOR.message_types_by_name['DeviceCommandProto'] = _DEVICECOMMANDPROTO
DESCRIPTOR.message_types_by_name['DeviceCommandResProto'] = _DEVICECOMMANDRESPROTO

DeviceCommandProto = _reflection.GeneratedProtocolMessageType('DeviceCommandProto', (_message.Message,), dict(
  DESCRIPTOR = _DEVICECOMMANDPROTO,
  __module__ = 'CommandMsg_pb2'
  # @@protoc_insertion_point(class_scope:schemas.DeviceCommandProto)
  ))
_sym_db.RegisterMessage(DeviceCommandProto)

DeviceCommandResProto = _reflection.GeneratedProtocolMessageType('DeviceCommandResProto', (_message.Message,), dict(
  DESCRIPTOR = _DEVICECOMMANDRESPROTO,
  __module__ = 'CommandMsg_pb2'
  # @@protoc_insertion_point(class_scope:schemas.DeviceCommandResProto)
  ))
_sym_db.RegisterMessage(DeviceCommandResProto)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n!com.segmetics.ng.protocol.message'))
# @@protoc_insertion_point(module_scope)
