# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AckMsg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AckMsg.proto',
  package='schemas',
  serialized_pb=_b('\n\x0c\x41\x63kMsg.proto\x12\x07schemas\";\n\x08\x41\x63kProto\x12\r\n\x05msgId\x18\x01 \x02(\t\x12\x0f\n\x07version\x18\x02 \x02(\x05\x12\x0f\n\x07payload\x18\x03 \x01(\tB#\n!com.segmetics.ng.protocol.message')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ACKPROTO = _descriptor.Descriptor(
  name='AckProto',
  full_name='schemas.AckProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgId', full_name='schemas.AckProto.msgId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='schemas.AckProto.version', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payload', full_name='schemas.AckProto.payload', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['AckProto'] = _ACKPROTO

AckProto = _reflection.GeneratedProtocolMessageType('AckProto', (_message.Message,), dict(
  DESCRIPTOR = _ACKPROTO,
  __module__ = 'AckMsg_pb2'
  # @@protoc_insertion_point(class_scope:schemas.AckProto)
  ))
_sym_db.RegisterMessage(AckProto)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n!com.segmetics.ng.protocol.message'))
# @@protoc_insertion_point(module_scope)
